services:
  abioticfactor:
    image: diyagi/abioticfactor-server-docker:latest
    container_name: abiotic-factor-server
    ports:
      - 7777:7777/udp
      #- 27015:27015/udp #Optional, only needed for the server to show in steam's server list
    environment:
      PUID: 1000
      PGID: 1000
      GSMAXSERVERPLAYERS: 6
      GSPORT: 7777
      GSQUERYPORT: 27015
      GSWORLDSAVENAME: ""
      GSSERVERPASSWORD: ""
      GSSERVERNAME: "Abiotic Factor Docker"
    volumes:
      - host-path:/abiotic-factor
      